### ISSUE TITLE
filter prefix

### ISSUE THREAD

**Issue by indiejoseph** [g45t345rt/superkv#1]
Thanks for your work, this library is what i looking for!

I have question about filter, in the example the prefix filter is defined with a fixed condition `metadata.points > 500`, is it able to make the condition dynamic? `(metadata, value) => metadata.points > value`?

**Comment by g45t345rt** [comment]
No you have to use a static value :S That's because KV storage is not consistent.
I don't recommend using the `KVTable` class of this library but the other classes are really useful `KVNamespaceApi`, `KVApi`, `KVBatch` and `KVBig`

If you want to implement dynamic sorting conditions or anything with indexes, you have to use DurableObject along side KV.
That is where the power lies. I have a working project but it's private for now.

Cheers!

**Comment by indiejoseph** [comment]
@g45t345rt thanks for your reply, yes shifted to DurableObject, and found storage API much more flexible, with pagination + revert order, in conjunction with ulid solved my problem
